### ISSUE TITLE
Project Idea Feedback

### ISSUE THREAD

**Issue by bursteinalan** [CS521-Burstein/final-project-rosssheng#1]
-Deliverable not met

**Comment by rosssheng** [comment]
Sorry, what was the deliverable not being met?

**Comment by bursteinalan** [comment]
The Project Idea

**Comment by rosssheng** [comment]
Thank you, we forgot that we had to declare our project option. We just declared it. Additionally, we finished our code to download the csv file, but we are not sure if this is sufficient. Would you be able to look over this code and see if it is okay for the second deliverable? 

Thank you.
